# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{inputs, ...}: {
  configurations.nixos.heliosmac = {
    config,
    lib,
    pkgs,
    modulesPath,
    ...
  }: {
    imports = [
      (modulesPath + "/hardware/network/broadcom-43xx.nix")
      (modulesPath + "/installer/scan/not-detected.nix")
      inputs.nixos-hardware.nixosModules.apple-macbook-pro-11-4
    ];

    boot.initrd.availableKernelModules = ["xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod"];
    boot.initrd.kernelModules = [];
    boot.kernelModules = ["kvm-intel"];
    boot.extraModulePackages = [];

    fileSystems."/" = {
      device = "/dev/mapper/luks-bdd2f8de-8636-4300-9c22-37e47e293aa0";
      fsType = "ext4";
    };

    boot.initrd.luks.devices."luks-bdd2f8de-8636-4300-9c22-37e47e293aa0".device = "/dev/disk/by-uuid/bdd2f8de-8636-4300-9c22-37e47e293aa0";

    fileSystems."/boot" = {
      device = "/dev/disk/by-uuid/8E27-487D";
      fsType = "vfat";
      options = ["fmask=0077" "dmask=0077"];
    };

    swapDevices = [
      {device = "/dev/mapper/luks-6e4b780a-fb7c-4d33-b934-b72f6a3b98f4";}
    ];

    nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
    hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  };
}
