export HOME="$TMPDIR/home"
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_STATE_HOME="$HOME/.local/state"
mkdir -p "$HOME"
profile="$TMPDIR/profile with spaces"
"$brave/bin/brave-sync" --user-data-dir "$profile" --profile-directory 'Profile 2'
test ! -e "$XDG_CONFIG_HOME/mybrave"
test -f "$profile/External Extensions/nngceckbapebfimnlniiiahkandclblb.json"
test ! -L "$profile/External Extensions/nngceckbapebfimnlniiiahkandclblb.json"
jq -e '.external_update_url == "https://clients2.google.com/service/update2/crx"' "$profile/External Extensions/nngceckbapebfimnlniiiahkandclblb.json"
prefs="$profile/Profile 2/Preferences"
jq -e '.credentials_enable_service == false and .credentials_enable_autosignin == false' "$prefs"
cat > "$prefs" <<'JSON'
{"credentials_enable_service":true,"bookmark_bar":{"show_on_all_tabs":true},"extensions":{"settings":{"secret":"private"}},"protection":{"macs":{"secret":"private"}},"download":{"default_directory":"/home/private/Downloads"},"profile":{"exit_type":"Normal"},"test_array":[{"keep":1,"token":"private"}]}
JSON
"$brave/bin/brave-snapshot" "$TMPDIR/captured.json" --user-data-dir="$profile" --profile-directory='Profile 2'
jq -e '.bookmark_bar.show_on_all_tabs and .credentials_enable_service and (has("extensions")|not) and (has("protection")|not) and (has("download")|not) and (has("test_array")|not)' "$TMPDIR/captured.json"
"$brave/bin/brave-sync" --user-data-dir "$profile" --profile-directory 'Profile 2'
jq -e '.credentials_enable_service == false and .bookmark_bar.show_on_all_tabs == true and .extensions.settings.secret == "private"' "$prefs"
# An invalid Preferences file aborts integration-file changes too.
printf '{invalid' > "$prefs"
printf '{"sentinel":true}' > "$profile/External Extensions/nngceckbapebfimnlniiiahkandclblb.json"
if "$brave/bin/brave-sync" --user-data-dir "$profile" --profile-directory 'Profile 2'; then exit 1; fi
jq -e '.sentinel' "$profile/External Extensions/nngceckbapebfimnlniiiahkandclblb.json"
test -s "$profile/Profile 2/.Preferences.sync-error.log"
cp "$TMPDIR/captured.json" "$TMPDIR/before.json"
if "$brave/bin/brave-snapshot" "$TMPDIR/captured.json" --user-data-dir "$profile" --profile-directory 'Profile 2'; then exit 1; fi
cmp "$TMPDIR/before.json" "$TMPDIR/captured.json"
test -s "$TMPDIR/.captured.json.snapshot-error.log"
# Actual launcher adapter, fake app: sync failure must not suppress app execution.
profile_tool=$(sed -n 's/^exec \([^ ]*\) sync .*$/\1/p' "$brave/bin/brave-sync")
cat > "$TMPDIR/fake-app" <<'SH'
#!/bin/sh
printf '%s\n' "$@" > "$CAPTURE"
exit 23
SH
# The sandbox has no /bin/sh; use the same interpreter as the packaged helper.
head -n 1 "$brave/bin/brave-sync" > "$TMPDIR/fake-executable"
tail -n +2 "$TMPDIR/fake-app" >> "$TMPDIR/fake-executable"
chmod +x "$TMPDIR/fake-executable"
export CAPTURE="$TMPDIR/arguments"
status=0
"$profile_tool" launch "$TMPDIR/fake-executable" --user-data-dir "$profile" --profile-directory 'Profile 2' 'https://example.org/a b' || status=$?
test "$status" = 23
grep -Fx 'https://example.org/a b' "$CAPTURE"
# Open-browser lock preserves even malformed prefs and still launches.
ln -s test-host-123 "$profile/SingletonLock"
status=0
"$profile_tool" launch "$TMPDIR/fake-executable" --user-data-dir "$profile" || status=$?
test "$status" = 23
if "$brave/bin/brave-sync" --user-data-dir "$profile"; then exit 1; fi
rm "$profile/SingletonLock"
# Snapshot must not silently succeed before a profile has produced Preferences.
if "$brave/bin/brave-snapshot" "$TMPDIR/missing.json" --user-data-dir "$TMPDIR/missing-profile"; then exit 1; fi
test ! -e "$TMPDIR/missing.json"
# A snapshot generated by brave-snapshot is embedded in a second wrapper using
# HM flags and a native-host declaration. Explicit settings still win over it.
"$braveRoundtrip/bin/brave-sync" --user-data-dir "$TMPDIR/roundtrip"
jq -e '.bookmark_bar.show_on_all_tabs and .credentials_enable_service == false and (has("extensions")|not)' "$TMPDIR/roundtrip/Default/Preferences"
jq -e '.name == "org.example.test"' "$TMPDIR/roundtrip/NativeMessagingHosts/org.example.test.json"
printf '{"runtime_only":true}' > "$TMPDIR/roundtrip/Default/Preferences"
"$braveRoundtrip/bin/brave-sync" --user-data-dir "$TMPDIR/roundtrip"
jq -e '. == {"runtime_only":true}' "$TMPDIR/roundtrip/Default/Preferences"
# Export must reject symlink leaves rather than overwrite their referents.
printf '{"unchanged":true}' > "$TMPDIR/real.json"
ln -s "$TMPDIR/real.json" "$TMPDIR/link.json"
if "$brave/bin/brave-snapshot" "$TMPDIR/link.json" --user-data-dir "$TMPDIR/roundtrip"; then exit 1; fi
jq -e '.unchanged' "$TMPDIR/real.json"
touch "$out"
