services:
  shelfmark:
    image: ghcr.io/calibrain/shelfmark:latest
    container_name: shelfmark
    environment:
      PUID: 1000
      PGID: 1000
    ports:
      - 8084:8084
    restart: unless-stopped
    network_mode: host
    volumes:
      - /var/lib/audiobooks:/books # Default destination for book downloads
      - /var/lib/shelfmark/config:/config # App configuration
      # Required for torrent / usenet - path must match your download client's volume exactly
      - /var/lib/qBittorrent/qBittorrent/audiobooks:/var/lib/qBittorrent/qBittorrent/audiobooks
