"""Filter settings.toml into a portable synced.toml snapshot."""
import argparse
import os
from pathlib import Path
import re
import tempfile
import tomllib

import tomli_w

DROP = object()
# Whole layouts contain instance IDs, monitor geometry, and cross-references.
LOCAL_SECTIONS = {"desktop_widgets", "lockscreen_widgets", "hooks", "include"}
LOCAL_KEYS = {
    "monitor", "monitors", "output", "outputs", "screen", "screens",
    "connector", "connectors", "monitor_overrides", "screen_overrides",
    "device", "devices", "device_id", "device_name", "backlight",
    "account", "accounts", "password", "token", "secret", "credentials",
    "latitude", "longitude", "city", "country", "address",
    "settings_expand_all_groups",
}
CONNECTOR = re.compile(r"(?:^|[@\s])(?:DP|HDMI-A|HDMI|eDP|DVI-D|DVI-I|VGA|DisplayPort)-\d+(?:-\d+)*(?:$|\s)")
# Check embedded paths too (commands, file URIs, and environment expansion).
PATH_TOKEN = re.compile(r"file://\S+|(?:~|\$\w+|\$\{[^}]+\})[^\s\"']*|(?<![\w:/])/(?!/)[^\s\"']+|(?:^|\s)\.{1,2}/\S+")


def local_string(value, key):
    if CONNECTOR.search(value):
        return True
    for match in PATH_TOKEN.finditer(value):
        token = match.group().strip()
        if not token.startswith("/nix/store/") or ".." in Path(token).parts:
            return True
    if key.endswith(("path", "paths", "directory", "directories", "file", "files", "folder", "folders")) and value:
        return not value.startswith("/nix/store/") or ".." in Path(value).parts
    return False


def prune(value, path=()):
    if isinstance(value, dict):
        result = {}
        for key, child in sorted(value.items()):
            lower = key.lower()
            if (not path and lower in LOCAL_SECTIONS) or lower in LOCAL_KEYS:
                continue
            if path == ("wallpaper",) and lower == "last":
                continue
            if CONNECTOR.search(key) or any(word in lower for word in ("password", "credential", "secret", "token")):
                continue
            cleaned = prune(child, (*path, key))
            if cleaned is not DROP:
                result[key] = cleaned
        return result if result else DROP
    if isinstance(value, list):
        cleaned = [prune(item, path) for item in value]
        # Do not silently change positional lists or retain half an entity.
        return DROP if any(item is DROP for item in cleaned) else cleaned
    if isinstance(value, str) and local_string(value, path[-1] if path else ""):
        return DROP
    return value


def atomic_write(path, data):
    fd, temporary = tempfile.mkstemp(prefix=f".{path.name}.", dir=path.parent)
    try:
        with os.fdopen(fd, "w") as stream:
            stream.write(data)
            stream.flush()
            os.fsync(stream.fileno())
        os.replace(temporary, path)
    finally:
        if os.path.exists(temporary):
            os.unlink(temporary)


def sync(source, destination):
    if not source.exists():
        return
    if destination.is_symlink() or source.resolve() == destination.resolve():
        raise RuntimeError("Destination must be a separate regular file")
    cleaned = prune(tomllib.loads(source.read_text()))
    text = "# Generated by noctalia-sync-preferences; review before committing.\n"
    text += tomli_w.dumps({} if cleaned is DROP else cleaned)
    if not destination.exists() or destination.read_text() != text:
        atomic_write(destination, text)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("source", type=Path)
    parser.add_argument("destination", type=Path)
    args = parser.parse_args()
    try:
        sync(args.source, args.destination)
    except (OSError, ValueError, RuntimeError) as error:
        parser.exit(1, f"noctalia-sync-preferences: {error}\n")
