"""Merge config.toml with pruned GUI overrides, then remove Nix store paths."""
import argparse
import os
from pathlib import Path
import re
import tempfile
import tomllib

import tomli_w

DROP = object()
# Whole layouts contain instance IDs, monitor geometry, and cross-references.
LOCAL_SECTIONS = {"desktop_widgets", "lockscreen_widgets", "hooks", "include"}
LOCAL_KEYS = {
    "config_version",
    "monitor", "monitors", "output", "outputs", "screen", "screens",
    "connector", "connectors", "monitor_overrides", "screen_overrides",
    "device", "devices", "device_id", "device_name", "backlight",
    "account", "accounts", "password", "token", "secret", "credentials",
    "latitude", "longitude", "city", "country", "address",
}
CONNECTOR = re.compile(r"(?:^|[@\s])(?:DP|HDMI-A|HDMI|eDP|DVI-D|DVI-I|VGA|DisplayPort)-\d+(?:-\d+)*(?:$|\s)")
# Check embedded paths too (commands, file URIs, and environment expansion).
PATH_TOKEN = re.compile(r"file://\S+|(?:~|\$\w+|\$\{[^}]+\})[^\s\"']*|(?<![\w:/])/(?!/)[^\s\"']+|(?:^|\s)\.{1,2}/\S+")


def local_string(value, key):
    if CONNECTOR.search(value):
        return True
    if PATH_TOKEN.search(value):
        return True
    if key.endswith(("path", "paths", "directory", "directories", "file", "files", "folder", "folders")) and value:
        return True
    return False


def prune(value, path=()):
    if isinstance(value, dict):
        result = {}
        for key, child in sorted(value.items()):
            lower = key.lower()
            if (not path and lower in LOCAL_SECTIONS) or lower in LOCAL_KEYS:
                continue
            if path == ("wallpaper",) and lower == "last":
                continue
            if CONNECTOR.search(key) or any(word in lower for word in ("password", "credential", "secret", "token")):
                continue
            cleaned = prune(child, (*path, key))
            if cleaned is not DROP:
                result[key] = cleaned
        return result if result else DROP
    if isinstance(value, list):
        cleaned = [prune(item, path) for item in value]
        # Do not silently change positional lists or retain half an entity.
        return DROP if any(item is DROP for item in cleaned) else cleaned
    if isinstance(value, str) and local_string(value, path[-1] if path else ""):
        return DROP
    return value


def atomic_write(path, data):
    fd, temporary = tempfile.mkstemp(prefix=f".{path.name}.", dir=path.parent)
    try:
        with os.fdopen(fd, "w") as stream:
            stream.write(data)
            stream.flush()
            os.fsync(stream.fileno())
        os.replace(temporary, path)
    finally:
        if os.path.exists(temporary):
            os.unlink(temporary)


def prune_store_paths(value):
    """Remove build-specific values from either layer without pruning baseline preferences."""
    if isinstance(value, dict):
        result = {}
        for key, child in value.items():
            cleaned = prune_store_paths(child)
            if cleaned is not DROP:
                result[key] = cleaned
        return result if result or not value else DROP
    if isinstance(value, list):
        cleaned = [prune_store_paths(item) for item in value]
        return DROP if any(item is DROP for item in cleaned) else cleaned
    if isinstance(value, str) and "/nix/store/" in value:
        return DROP
    return value


def merge(baseline, overrides):
    result = dict(baseline)
    for key, value in overrides.items():
        if isinstance(value, dict) and isinstance(result.get(key), dict):
            result[key] = merge(result[key], value)
        else:
            result[key] = value
    return result


def snapshot(config_file, settings_file, destination):
    if destination.is_symlink() or destination.resolve() in {
        config_file.resolve(), settings_file.resolve()
    }:
        raise RuntimeError("Destination must be a separate regular file")
    baseline = tomllib.loads(config_file.read_text())
    overrides = tomllib.loads(settings_file.read_text()) if settings_file.exists() else {}
    cleaned = prune(overrides)
    combined = merge(baseline, {} if cleaned is DROP else cleaned)
    combined = prune_store_paths(combined)
    text = "# Generated by noctalia-snapshot-preferences; review before committing.\n"
    text += tomli_w.dumps({} if combined is DROP else combined)
    if not destination.exists() or destination.read_text() != text:
        atomic_write(destination, text)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("config", type=Path)
    parser.add_argument("settings", type=Path)
    parser.add_argument("destination", type=Path)
    args = parser.parse_args()
    try:
        snapshot(args.config, args.settings, args.destination)
    except (OSError, ValueError, RuntimeError) as error:
        parser.exit(1, f"noctalia-snapshot-preferences: {error}\n")
